# COSC 311: Introduction to Data Visualization and Interpretation

Instructor: Dr. Shuangquan (Peter) Wang

Email: spwang@salisbury.edu

Department of Computer Science, Salisbury University


# Module 2_Data Processing and Organization

## 2. Numerial tools



**Contents of this note refer to 1) Dr. Joe Anderson's teaching materials; 2) textbook "Data Science from Scratch"; 3) https://www.w3schools.com/python/numpy/default.asp**

**<font color=red>All rights reserved. Dissemination or sale of any part of this note is NOT permitted.</font>**

# NumPy

https://numpy.org/

NumPy stands for Numerical Python. NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays (https://en.wikipedia.org/wiki/NumPy).

Functions in NumPy: https://numpy.org/doc/stable/reference/routines.html

Example:

numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

- return evenly spaced values within a given interval.

## Create arrays using Numpy

Refer to https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp

NumPy is used to work with arrays. The array object in NumPy is called *ndarray*. A NumPy *ndarray* object can be created by using the **array()** function.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


array() function can convert a list, tuple or any array-like object into an array.

In [3]:
# e.g. tuple

arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


## 2-D Arrays

An array that has 1-D arrays as its elements. 2-D arrays are often used to represent matrix.

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr) #two 2D matrix in one matrix
for x in arr:
    for y in x:
        for z in y:
            print(z)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6


NumPy provides the **ndim** attribute that returns an integer represents the dimensions of the array.

In [6]:
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])

print(b.ndim)
print(c.ndim)


1
2


## Access Array Elements

You can access an array element by referring to its index number.
To access elements from 2-D arrays you can use comma separated indices for row and column.

In [7]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


Iterating arrays

In [9]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


## Sorting Arrays

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [18]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
print(arr)

[0 1 2 3]
[3 2 0 1]


## Calculation between two arrays

In [13]:
x = np.array([1,2,3,4])
y = np.array([4,5,6,7])

In [14]:
# array + array
print(x + y)

[ 5  7  9 11]


In [15]:
# array + number
print(x + 2)

[3 4 5 6]


It is different with list calculation

In [16]:
# list + list
x = [1,2,3,4]
y = [4,5,6,7]
z = x + y
print(z)

[1, 2, 3, 4, 4, 5, 6, 7]


In [17]:
# list + number (syntax error)
print(x + 2)

TypeError: can only concatenate list (not "int") to list

Other array operations:

In [28]:
x = np.array([1,2,3,4])
y = np.array([16, 16, 16, 16])
print(np.sqrt(x))
print(np.sqrt(y))

[1.         1.41421356 1.73205081 2.        ]
[4. 4. 4. 4.]


In [29]:
x = np.array([1,2,3,4])

x * 10

array([10, 20, 30, 40])

Array * Array is element-wise multiplication

In [30]:
A = np.array([
    [2,3,4],
    [3,1,0],
    [0,1,1]
])

x = np.array([1,3,4])

In [31]:
A * x  # will broadcast the 1x3 into a 3x3 by vertically copying,
       # then does element-wise multiplication

array([[ 2,  9, 16],
       [ 3,  3,  0],
       [ 0,  3,  4]])

How to do matrix multiply with matrix?

In [32]:
A = np.arange(1,5).reshape(2,2)
print(A)
B = np.arange(0,4).reshape(2,2)
print(B)
print(type(A))
print(type(B))

[[1 2]
 [3 4]]
[[0 1]
 [2 3]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [39]:
x = np.arange(1,5)
print(x)
print(x.reshape(2, 2))

[1 2 3 4]
[[1 2]
 [3 4]]


In [47]:
print(A * B)   # array multiplication: element-wise multiplication)
A @ B

[[ 0  2]
 [ 6 12]]


array([[ 4,  7],
       [ 8, 15]])

In [41]:
C = np.mat(A)
print(C)
D = np.mat(B)
print(D)
print(type(C))
print(type(D))


[[1 2]
 [3 4]]
[[0 1]
 [2 3]]
<class 'numpy.matrix'>
<class 'numpy.matrix'>


In [42]:
# matrix multiplication
C * D #first row times first column, first row times second column, second row times first column, second rown times seond colmn

matrix([[ 4,  7],
        [ 8, 15]])

# pandas

pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. -- Wikipedia

In [48]:
import pandas as pd # our main priority here
import numpy as np  # just in case, but also comes along with pandas
from matplotlib import pyplot as plt # for plotting

In [49]:
# dictionary that holds the wins, draws, and losses for three 
# football (soccer) teams over three years. This is realized 
# in a simple way by just doing nine rows, where each row has
# the year, team, wins, draws, and losses.

football_data = { 
    'year': [
        2010, 2011, 2012,
        2010, 2011, 2012,
        2010, 2011, 2012
        ],
    'team': [
        'FCBarcelona', 'FCBarcelona',
        'FCBarcelona', 'RMadrid',
        'RMadrid', 'RMadrid',
        'ValenciaCF', 'ValenciaCF',
        'ValenciaCF'
    ],
    'wins':[30 , 28 , 32 , 29 , 32 , 26 , 21 , 17 , 19] ,
    'draws': [6 , 7 , 4 , 5 , 4 , 7 , 8 , 10 , 8] ,
    'losses': [2 , 3 , 2 , 4 , 2 , 5 , 9 , 11 , 11]
}

# The task: now we want to manipulate and present this data

In [50]:
# how many wins did FCB have in 2010?
print(football_data['wins'][0]) 

# how many wins did RMadrid have in 2011?
print(football_data['wins'][4])

print(football_data)

30
32
{'year': [2010, 2011, 2012, 2010, 2011, 2012, 2010, 2011, 2012], 'team': ['FCBarcelona', 'FCBarcelona', 'FCBarcelona', 'RMadrid', 'RMadrid', 'RMadrid', 'ValenciaCF', 'ValenciaCF', 'ValenciaCF'], 'wins': [30, 28, 32, 29, 32, 26, 21, 17, 19], 'draws': [6, 7, 4, 5, 4, 7, 8, 10, 8], 'losses': [2, 3, 2, 4, 2, 5, 9, 11, 11]}


The main object of interest here is called a DataFrame. Refer to the [User Guide](https://pandas.pydata.org/docs/user_guide/index.html) of pandas:

https://pandas.pydata.org/docs/reference/frame.html

In [51]:
#football_df = pd.DataFrame(football_data, columns=['year', 'team', 'wins', 'draws', 'losses'])
football_df = pd.DataFrame(football_data)
print(football_df) # show the object as plain text

   year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11
8  2012   ValenciaCF    19      8      11


In [59]:
football_df

football_df.to_excel("output.xlsx")

In [52]:
football_df.head(2)

year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3

In [54]:
football_df[2:] # we can slice similar to python lists!
                # gets every row from index 2 onward

year         team  wins  draws  losses
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11
8  2012   ValenciaCF    19      8      11

In [55]:
football_df['team'] # get a whole column

0    FCBarcelona
1    FCBarcelona
2    FCBarcelona
3        RMadrid
4        RMadrid
5        RMadrid
6     ValenciaCF
7     ValenciaCF
8     ValenciaCF
Name: team, dtype: object

In [56]:
football_df[ ['team', 'wins', 'draws'] ] # get three whole columns

team  wins  draws
0  FCBarcelona    30      6
1  FCBarcelona    28      7
2  FCBarcelona    32      4
3      RMadrid    29      5
4      RMadrid    32      4
5      RMadrid    26      7
6   ValenciaCF    21      8
7   ValenciaCF    17     10
8   ValenciaCF    19      8

In [57]:
# add a new column
football_df['m_index'] = np.array(list(football_df.index)) + 1
football_df

year         team  wins  draws  losses  m_index
0  2010  FCBarcelona    30      6       2        1
1  2011  FCBarcelona    28      7       3        2
2  2012  FCBarcelona    32      4       2        3
3  2010      RMadrid    29      5       4        4
4  2011      RMadrid    32      4       2        5
5  2012      RMadrid    26      7       5        6
6  2010   ValenciaCF    21      8       9        7
7  2011   ValenciaCF    17     10      11        8
8  2012   ValenciaCF    19      8      11        9

In [60]:
# run some basic statistics on the numerical columns in the dataframe
football_df.describe()

year       wins      draws     losses   m_index
count     9.000000   9.000000   9.000000   9.000000  9.000000
mean   2011.000000  26.000000   6.555556   5.444444  5.000000
std       0.866025   5.656854   2.006932   3.844188  2.738613
min    2010.000000  17.000000   4.000000   2.000000  1.000000
25%    2010.000000  21.000000   5.000000   2.000000  3.000000
50%    2011.000000  28.000000   7.000000   4.000000  5.000000
75%    2012.000000  30.000000   8.000000   9.000000  7.000000
max    2012.000000  32.000000  10.000000  11.000000  9.000000

In [61]:
# basic stats operations can be run over dataframes
means = football_df[['wins', 'draws']].mean() # gives a dictionary-like result object
print(means)
type(means) # pandas.core.series.Series

wins     26.000000
draws     6.555556
dtype: float64


pandas.core.series.Series

In [62]:
# can also unzip: wins, draws to extract both in parallel
means = football_df[['wins']].mean()
print(means)
type(means)

wins    26.0
dtype: float64


pandas.core.series.Series

In [63]:
means = football_df[['draws']].mean()
print(means)
type(means)

draws    6.555556
dtype: float64


pandas.core.series.Series

In [64]:
# pay attention to the difference
means = football_df['wins'].mean()
print(means)
type(means)

26.0


float

Why?

In [65]:
type(football_df[['wins']])

pandas.core.frame.DataFrame

In [66]:
type(football_df['wins'])

pandas.core.series.Series

In [67]:
# extract all the RM data:
football_df['team'] == 'RMadrid' 
# results in a list/sequence of booleans, after doing element-wise testing!

print(football_df['team'] == 'RMadrid')


0    False
1    False
2    False
3     True
4     True
5     True
6    False
7    False
8    False
Name: team, dtype: bool


In [ ]:
# we can select rows by using boolean indexing
# so combining these ideas:
football_df[ football_df['team'] == 'RMadrid' ]

In [ ]:
# also combining booleans lists/series with bitwise-operators
print(football_df['team'] == 'RMadrid')
print(football_df['team'] == 'ValenciaCF')

# use bitwise OR (the single pipe, |) to combine:
print( (football_df['team'] == 'RMadrid') | (football_df['team'] == 'ValenciaCF') )

In [ ]:
football_df[ (football_df['team'] == 'RMadrid') | (football_df['team'] == 'ValenciaCF') ]

In [ ]:
football_df[football_df['team'] == 'FCBarcelona']

In [ ]:
# DataFrames have built-in plotting!
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.bar.html

football_df[football_df['team'] == 'FCBarcelona'].plot.bar(x='year', y='wins', 
   color=['b', 'r', 'g'], 
   title='FC Barcelona Wins from 2010 to 2012',
   xlabel='Year',
   ylabel='Wins'
   )

In [ ]:
football_df[(football_df['team'] == 'FCBarcelona') | (football_df['team'] == 'ValenciaCF')].plot.bar(x='year', y='wins', 
   color=['b', 'r', 'g'], 
   title='Barcelona & Valencia Wins from 2010 to 2012',
   xlabel='Year',
   ylabel='Wins'
   )

In [ ]:
fcb_vcf_wins = football_df[(football_df['team'] == 'FCBarcelona') \
                           | (football_df['team'] == 'ValenciaCF')][['year','team','wins']]
fcb_vcf_wins

In [ ]:
# DataFrame.pivot: Return reshaped DataFrame organized by given index / column values.
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html

fcb_vcf_wins_pivoted = fcb_vcf_wins.pivot(index='year', columns='team', values='wins')
fcb_vcf_wins_pivoted

In [ ]:
fcb_vcf_wins_pivoted.plot(kind='bar')

Take CSV file as the data source

In [ ]:
# The file path is ***RELATIVE TO THIS NOTEBOOK***
# https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
housing_data = pd.read_csv('housing.csv')

In [ ]:
housing_data.info()

In [ ]:
housing_data['ocean_proximity']

In [ ]:
housing_data['ocean_proximity'].unique()

# Using and Analyzing Data

## Questions that the housing data could potentially answer:

- What is the average amount of bedrooms in houses?
- What is the average distance from the ocean?
- How does income/house value correspond to ocean proximity?
- Does location (ocean proximity) affect size of house or number of bedrooms?
- Breakdown of attributes per-state (size, income, etc) using lat/long
- Where do people retire?


In [ ]:
housing_data.describe()

In [ ]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.scatter.html

housing_data.plot.scatter(x = 'longitude', y = 'latitude')

In [ ]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.hist.html

housing_data.plot.hist(by='median_house_value', bins=10)

In [ ]:
housing_data['median_house_value'].plot(kind='hist',bins=100)

In [ ]:
housing_data['ocean_proximity'].count()

In [ ]:
housing_data[['median_house_value','ocean_proximity']].\
groupby('ocean_proximity').count().plot(kind='bar')